### ISSUE TITLE
automation annotation is not good as readme

### ISSUE THREAD

**Issue by hefc2016** [ziliHarvey/smart-annotation-pointrcnn#10]
Hello,

thanks for sharing this project.

I have tried this tool from my side and using automation annotation feature by hold A key, but the result is not good as your demo.

Could you give more suggestion that how can I get better result? Do I need to train the model 
again?
![Screenshot from 2020-10-12 22-22-05](https://user-images.githubusercontent.com/24312605/95757388-ab852b80-0cd9-11eb-904c-c6485ecef7bf.png)

**Comment by ziliHarvey** [comment]
Pressing "A" will not run deep learning model, it's simply using some clustering method to generate the 3D bounding box. Details is in /docs folder. For running PointRCNN for prediction, try check the box "Fully automated annotation". If you are using the data I provided, you don't need to re-train the model.

**Comment by hefc2016** [comment]
yes, I have checked the box "Fully automated annotation". but the 3D bounding box are not created automatically, there is no error log print in the terminal. I guess the PointRCNN is not running in backend.

I am using the data you provided in the repo, and where is the pre-trained PointRCNN model?

**Comment by hefc2016** [comment]
Hello, 

I re-run the eval_rcnn.py again to get the evaluate result and I can see the automation 3D bbox now after I checked the box "Fully automated annotation".

![Screenshot from 2020-10-13 21-28-35](https://user-images.githubusercontent.com/24312605/95866944-23fff100-0d9b-11eb-9fe9-a332aa76d266.png)

and I have another question:
Is the bottom edge line of bbox which has 3 adjust points means the head of vehicle?

**Comment by ziliHarvey** [comment]
> yes, I have checked the box "Fully automated annotation". but the 3D bounding box are not created automatically, there is no error log print in the terminal. I guess the PointRCNN is not running in backend.
> 
> I am using the data you provided in the repo, and where is the pre-trained PointRCNN model?

You should be able to check the box and have everything ready by itself, which may take relative long time for first time per your hardware. The details is in [preprocess.py](https://github.com/ziliHarvey/smart-annotation-pointrcnn/blob/master/app/preprocess.py), it will be called automatically once you check the box and then run pointrcnn. If you manually type and run eval_rcnn.py, that breaks the purpose and is not the correct way to use this tool and I'm not sure what will happen by doing this. 

The pre-trained model file is in `--rcnn_ckpt checkpoint_epoch_40.pth --rpn_ckpt checkpoint_epoch_50.pth` as can be found in [preprocess.py](https://github.com/ziliHarvey/smart-annotation-pointrcnn/blob/master/app/preprocess.py). 

And again for the purpose of this tool I would not suggest to modify any low-level structure since we want to make it handy to use. If you are interested in changing the structures or re-train the model, etc, please follow the /docs folder and read the code to figure out how everything runs.

**Comment by ziliHarvey** [comment]
> Hello,
> 
> I re-run the eval_rcnn.py again to get the evaluate result and I can see the automation 3D bbox now after I checked the box "Fully automated annotation".
> 
> ![Screenshot from 2020-10-13 21-28-35](https://user-images.githubusercontent.com/24312605/95866944-23fff100-0d9b-11eb-9fe9-a332aa76d266.png)
> 
> and I have another question:
> Is the bottom edge line of bbox which has 3 adjust points means the head of vehicle?

Yea, the extra adjust point gives you the freedom to adjust yaw angle. The rest 4 at the the corners gives the freedom to adjust size IIRC.

**Comment by hefc2016** [comment]
> > yes, I have checked the box "Fully automated annotation". but the 3D bounding box are not created automatically, there is no error log print in the terminal. I guess the PointRCNN is not running in backend.
> > I am using the data you provided in the repo, and where is the pre-trained PointRCNN model?
> 
> You should be able to check the box and have everything ready by itself, which may take relative long time for first time per your hardware. The details is in [preprocess.py](https://github.com/ziliHarvey/smart-annotation-pointrcnn/blob/master/app/preprocess.py), it will be called automatically once you check the box and then run pointrcnn. If you manually type and run eval_rcnn.py, that breaks the purpose and is not the correct way to use this tool and I'm not sure what will happen by doing this.
> 
> The pre-trained model file is in `--rcnn_ckpt checkpoint_epoch_40.pth --rpn_ckpt checkpoint_epoch_50.pth` as can be found in [preprocess.py](https://github.com/ziliHarvey/smart-annotation-pointrcnn/blob/master/app/preprocess.py).
> 
> And again for the purpose of this tool I would not suggest to modify any low-level structure since we want to make it handy to use. If you are interested in changing the structures or re-train the model, etc, please follow the /docs folder and read the code to figure out how everything runs.

ok, thank you for your detail explanation . 

I think there is some dependency library issue in my environment,  will re-install the necessary libraries and follow the docs to run this project again.
